# Generated by Django 4.0.1 on 2022-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finalcopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=200)),
                ('Location', models.TextField(max_length=200)),
                ('Submission_date', models.DateTimeField()),
                ('Proponent', models.TextField(max_length=200)),
                ('Consultant', models.TextField(max_length=200)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
