# Generated by Django 4.0.1 on 2022-01-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalcopy',
            old_name='Location',
            new_name='Project_Location',
        ),
    ]
