# Generated by Django 4.0.1 on 2022-01-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_finalcopy_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalcopy',
            old_name='Submission_date',
            new_name='Date',
        ),
    ]
