# Generated by Django 4.0.1 on 2022-01-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_rename_submission_date_finalcopy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalcopy',
            name='Date',
        ),
    ]
